name: Build and Push Nopaste Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Registry
        run: echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login docker.rihyette.fr -u "${{ secrets.REGISTRY_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t docker.rihyette.fr/nopaste:latest .
          docker push docker.rihyette.fr/nopaste:latest
